version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
    - ./config/Database.env
    - ./config/App.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    
volumes:
  postgres-data:
    driver: local